# EXPO needs a ip to run QRCode properly
# use make, do not use docker-compose up alone

version: "3"
services:
  front:
    build: mobile
    command: bash -c "bash"
    ports:
      - "19000:19000"
      - "19001:19001"
    env_file:
      - .env
    volumes:
      - ./mobile/:/app
    stdin_open: true
    tty: true
  mock:
    build: api-mock
    command: bash -c "npm install --save; npm run start:dev" 
    ports:
      - "8081:8081"
    volumes:
      - ./api-mock/:/app
    stdin_open: true
    tty: true
